### ISSUE TITLE
Please release a compiled version

### ISSUE THREAD

**Issue by Neboer** [dongdaxiaodong/mayuan#2]
Compiling an windows program needs VS and it's too big to be installed on my laptop.
Could you please publish a compiled version of this program? Thank you.

**Comment by A-new-b** [comment]
agree! And this pynut.exe seems doesn't work at my PC

**Comment by Neboer** [comment]
The issue is closed because it is wrongly raised by me for misunderstanding the usage of the repo. Thanks for your great work. I have tested it on my computer and it really works.

Now could you please upload your source code? If the questions are programmed directly in the program, it may be hard to modify.
